name: 'checks'

on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  checks:
    if: github.event.workflow_run.head_repository.owner.name != 'ni'
    runs-on: ubuntu-22.04
    steps:
    - run: 'echo We are doing our best'
